title: Hello, world! I'm Hiep BrSE
description: > # this means to ignore newlines until "baseurl:"
  My blog is used to note my share of the process of working as a BrSE.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://brsenote.com" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Hiep BrSE # add your name
author-img: hiep-avatar.jpg # add your photo
about-author: Mình thích công việc BrSE và đã làm BrSE được hơn 1 năm rồi. Trước đó thì là developer Java ở Nhật được tầm 3 năm. # add description
# social-twitter: # add your Twitter handle
social-facebook: https://www.facebook.com/hiepvh1003/# add your Facebook handle
# social-github: artemsheludko # add your Github handle
social-linkedin: https://www.linkedin.com/in/vo-hoang-hiep-368356194/# add your Linkedin handle
social-email: hiepvh1003@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 5
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
